title: Project FileMaker
author: Bankyo
email: 2265@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My FileMaker Project.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
